Add RAM
Dasharo/TwPM_toplevel pull request #6
Opened 2023-06-19 17:04 UTC by krystian-hebel

2023-08-02 12:38 UTC, miczyg1 requested changes

2023-08-02 12:38 UTC, miczyg1 commented on fpga/Makefile
> -FPGA_RTL_SRC_PATHS:=verilog-lpc-module/lpc_defines.v
No longer need defines?

2023-08-02 12:38 UTC, miczyg1 commented on fpga/TwPM_Top.v
> +      abort
Why do we add something that will be removed?

2023-08-02 12:41 UTC, krystian-hebel commented on fpga/Makefile
> -FPGA_RTL_SRC_PATHS:=verilog-lpc-module/lpc_defines.v
They were never actually needed, those files don't introduce modules. They are included from files that do so files themselves must be present, but they don't have to be passed to Yosys through command line.

2023-08-02 14:56 UTC, miczyg1 commented on fpga/TwPM_Top.v
> +      abort
So it will be replaced later by something that will really utilize those signals/ports?

2023-08-02 14:58 UTC, krystian-hebel commented on fpga/TwPM_Top.v
> +      abort
Yes, it will eventually be connected through ABH to Wishbone bridge towards MCU.

2023-08-03 07:59 UTC, miczyg1 approved these changes

2023-08-03 09:11 UTC, merged